/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void Lab08() {
        Gson gson = new Gson();
        String jsonText0 = "{\"author\":\"Ali\",\"text\":\"Student0\"}";
        String jsonText1 = "{\"author\":\"Majd\",\"text\":\"Best Partner\"}";
        String jsonText2 = "{\"author\":\"Batool\",\"text\":\"TA's\"}";

        try{
            Reader reader = new FileReader("../app/src/main/resources/data.json");
            Quotes q1 = gson.fromJson(jsonText0,Quotes.class);
            Quotes q2 = gson.fromJson(jsonText1,Quotes.class);
            Quotes q3 = gson.fromJson(jsonText2,Quotes.class);
            Quotes[] q4 = gson.fromJson(reader , Quotes[].class);
            String str = "Quotes{author='Charles Dickens', text=' “It was one of those March days when the sun shines hot and the wind blows cold: when it is summer in the light, and winter in the shade.” '}";

            assertEquals("Quotes{author='Ali', text='Student0'}" , q1.toString());
            assertEquals("Quotes{author='Majd', text='Best Partner'}" , q2.toString());
            assertEquals("Quotes{author='Batool', text='TA's'}" , q3.toString());
            assertEquals(str , q4[2].toString());

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
